/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTalendRouteImport } from './routes/_authenticated/talend'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedDealsIndexRouteImport } from './routes/_authenticated/deals/index'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedProjectsListRouteImport } from './routes/_authenticated/projects/list'
import { Route as AuthenticatedProjectsCreateRouteImport } from './routes/_authenticated/projects/create'
import { Route as AuthenticatedDealsListRouteImport } from './routes/_authenticated/deals/list'
import { Route as AuthenticatedDealsCreateRouteImport } from './routes/_authenticated/deals/create'
import { Route as AuthenticatedCustomersListRouteImport } from './routes/_authenticated/customers/list'
import { Route as AuthenticatedCustomersCompanyIdRouteImport } from './routes/_authenticated/customers/$companyId'
import { Route as AuthenticatedProjectsTasksIndexRouteImport } from './routes/_authenticated/projects/tasks/index'
import { Route as AuthenticatedProjectsTasksCreateRouteImport } from './routes/_authenticated/projects/tasks/create'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTalendRoute = AuthenticatedTalendRouteImport.update({
  id: '/talend',
  path: '/talend',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDealsIndexRoute = AuthenticatedDealsIndexRouteImport.update({
  id: '/deals/',
  path: '/deals/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectsListRoute =
  AuthenticatedProjectsListRouteImport.update({
    id: '/projects/list',
    path: '/projects/list',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsCreateRoute =
  AuthenticatedProjectsCreateRouteImport.update({
    id: '/projects/create',
    path: '/projects/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDealsListRoute = AuthenticatedDealsListRouteImport.update({
  id: '/deals/list',
  path: '/deals/list',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDealsCreateRoute =
  AuthenticatedDealsCreateRouteImport.update({
    id: '/deals/create',
    path: '/deals/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomersListRoute =
  AuthenticatedCustomersListRouteImport.update({
    id: '/customers/list',
    path: '/customers/list',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomersCompanyIdRoute =
  AuthenticatedCustomersCompanyIdRouteImport.update({
    id: '/customers/$companyId',
    path: '/customers/$companyId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsTasksIndexRoute =
  AuthenticatedProjectsTasksIndexRouteImport.update({
    id: '/projects/tasks/',
    path: '/projects/tasks/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsTasksCreateRoute =
  AuthenticatedProjectsTasksCreateRouteImport.update({
    id: '/projects/tasks/create',
    path: '/projects/tasks/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/talend': typeof AuthenticatedTalendRoute
  '/customers/$companyId': typeof AuthenticatedCustomersCompanyIdRoute
  '/customers/list': typeof AuthenticatedCustomersListRoute
  '/deals/create': typeof AuthenticatedDealsCreateRoute
  '/deals/list': typeof AuthenticatedDealsListRoute
  '/projects/create': typeof AuthenticatedProjectsCreateRoute
  '/projects/list': typeof AuthenticatedProjectsListRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/customers/': typeof AuthenticatedCustomersIndexRoute
  '/deals/': typeof AuthenticatedDealsIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/projects/tasks/create': typeof AuthenticatedProjectsTasksCreateRoute
  '/projects/tasks/': typeof AuthenticatedProjectsTasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/talend': typeof AuthenticatedTalendRoute
  '/customers/$companyId': typeof AuthenticatedCustomersCompanyIdRoute
  '/customers/list': typeof AuthenticatedCustomersListRoute
  '/deals/create': typeof AuthenticatedDealsCreateRoute
  '/deals/list': typeof AuthenticatedDealsListRoute
  '/projects/create': typeof AuthenticatedProjectsCreateRoute
  '/projects/list': typeof AuthenticatedProjectsListRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/deals': typeof AuthenticatedDealsIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/projects/tasks/create': typeof AuthenticatedProjectsTasksCreateRoute
  '/projects/tasks': typeof AuthenticatedProjectsTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/talend': typeof AuthenticatedTalendRoute
  '/_authenticated/customers/$companyId': typeof AuthenticatedCustomersCompanyIdRoute
  '/_authenticated/customers/list': typeof AuthenticatedCustomersListRoute
  '/_authenticated/deals/create': typeof AuthenticatedDealsCreateRoute
  '/_authenticated/deals/list': typeof AuthenticatedDealsListRoute
  '/_authenticated/projects/create': typeof AuthenticatedProjectsCreateRoute
  '/_authenticated/projects/list': typeof AuthenticatedProjectsListRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/deals/': typeof AuthenticatedDealsIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/projects/tasks/create': typeof AuthenticatedProjectsTasksCreateRoute
  '/_authenticated/projects/tasks/': typeof AuthenticatedProjectsTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/admin'
    | '/dashboard'
    | '/settings'
    | '/talend'
    | '/customers/$companyId'
    | '/customers/list'
    | '/deals/create'
    | '/deals/list'
    | '/projects/create'
    | '/projects/list'
    | '/api/auth/$'
    | '/customers/'
    | '/deals/'
    | '/projects/'
    | '/projects/tasks/create'
    | '/projects/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/admin'
    | '/dashboard'
    | '/settings'
    | '/talend'
    | '/customers/$companyId'
    | '/customers/list'
    | '/deals/create'
    | '/deals/list'
    | '/projects/create'
    | '/projects/list'
    | '/api/auth/$'
    | '/customers'
    | '/deals'
    | '/projects'
    | '/projects/tasks/create'
    | '/projects/tasks'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/unauthorized'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/_authenticated/talend'
    | '/_authenticated/customers/$companyId'
    | '/_authenticated/customers/list'
    | '/_authenticated/deals/create'
    | '/_authenticated/deals/list'
    | '/_authenticated/projects/create'
    | '/_authenticated/projects/list'
    | '/api/auth/$'
    | '/_authenticated/customers/'
    | '/_authenticated/deals/'
    | '/_authenticated/projects/'
    | '/_authenticated/projects/tasks/create'
    | '/_authenticated/projects/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/talend': {
      id: '/_authenticated/talend'
      path: '/talend'
      fullPath: '/talend'
      preLoaderRoute: typeof AuthenticatedTalendRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/deals/': {
      id: '/_authenticated/deals/'
      path: '/deals'
      fullPath: '/deals/'
      preLoaderRoute: typeof AuthenticatedDealsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects/list': {
      id: '/_authenticated/projects/list'
      path: '/projects/list'
      fullPath: '/projects/list'
      preLoaderRoute: typeof AuthenticatedProjectsListRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/create': {
      id: '/_authenticated/projects/create'
      path: '/projects/create'
      fullPath: '/projects/create'
      preLoaderRoute: typeof AuthenticatedProjectsCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/deals/list': {
      id: '/_authenticated/deals/list'
      path: '/deals/list'
      fullPath: '/deals/list'
      preLoaderRoute: typeof AuthenticatedDealsListRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/deals/create': {
      id: '/_authenticated/deals/create'
      path: '/deals/create'
      fullPath: '/deals/create'
      preLoaderRoute: typeof AuthenticatedDealsCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers/list': {
      id: '/_authenticated/customers/list'
      path: '/customers/list'
      fullPath: '/customers/list'
      preLoaderRoute: typeof AuthenticatedCustomersListRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers/$companyId': {
      id: '/_authenticated/customers/$companyId'
      path: '/customers/$companyId'
      fullPath: '/customers/$companyId'
      preLoaderRoute: typeof AuthenticatedCustomersCompanyIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/tasks/': {
      id: '/_authenticated/projects/tasks/'
      path: '/projects/tasks'
      fullPath: '/projects/tasks/'
      preLoaderRoute: typeof AuthenticatedProjectsTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/tasks/create': {
      id: '/_authenticated/projects/tasks/create'
      path: '/projects/tasks/create'
      fullPath: '/projects/tasks/create'
      preLoaderRoute: typeof AuthenticatedProjectsTasksCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTalendRoute: typeof AuthenticatedTalendRoute
  AuthenticatedCustomersCompanyIdRoute: typeof AuthenticatedCustomersCompanyIdRoute
  AuthenticatedCustomersListRoute: typeof AuthenticatedCustomersListRoute
  AuthenticatedDealsCreateRoute: typeof AuthenticatedDealsCreateRoute
  AuthenticatedDealsListRoute: typeof AuthenticatedDealsListRoute
  AuthenticatedProjectsCreateRoute: typeof AuthenticatedProjectsCreateRoute
  AuthenticatedProjectsListRoute: typeof AuthenticatedProjectsListRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedDealsIndexRoute: typeof AuthenticatedDealsIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedProjectsTasksCreateRoute: typeof AuthenticatedProjectsTasksCreateRoute
  AuthenticatedProjectsTasksIndexRoute: typeof AuthenticatedProjectsTasksIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTalendRoute: AuthenticatedTalendRoute,
  AuthenticatedCustomersCompanyIdRoute: AuthenticatedCustomersCompanyIdRoute,
  AuthenticatedCustomersListRoute: AuthenticatedCustomersListRoute,
  AuthenticatedDealsCreateRoute: AuthenticatedDealsCreateRoute,
  AuthenticatedDealsListRoute: AuthenticatedDealsListRoute,
  AuthenticatedProjectsCreateRoute: AuthenticatedProjectsCreateRoute,
  AuthenticatedProjectsListRoute: AuthenticatedProjectsListRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedDealsIndexRoute: AuthenticatedDealsIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedProjectsTasksCreateRoute: AuthenticatedProjectsTasksCreateRoute,
  AuthenticatedProjectsTasksIndexRoute: AuthenticatedProjectsTasksIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
