# Generated by Django 6.0.7 on 2026-08-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EtlRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=64, unique=True)),
                ('trigger_type', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled')], max_length=16)),
                ('triggered_by', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=16)),
                ('returncode', models.IntegerField(blank=True, null=True)),
                ('output', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
