# Generated by Django 6.0.7 on 2026-08-07 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('industry', models.CharField(choices=[('banking_finance', 'Banking & Finance'), ('consulting', 'Consulting & Audit'), ('agro_food', 'Agro-food'), ('education', 'Education & Research'), ('telecom', 'Telecom'), ('retail', 'Retail & Distribution'), ('other', 'Other / Generic')], default='other', max_length=30)),
                ('service_category', models.CharField(choices=[('web_dev', 'Web Development'), ('digital_marketing', 'Digital Marketing'), ('bi_data', 'BI & Data'), ('hosting_maintenance', 'Hosting & Maintenance'), ('consulting_service', 'Consulting'), ('other', 'Other / Generic')], default='other', max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('is_default', models.BooleanField(default=False, help_text='Fallback template used when no industry/service match is found. Only one should be active at a time.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['industry', 'service_category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_company', models.IntegerField(db_index=True)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('role_title', models.CharField(blank=True, default='', max_length=150)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code_company', '-is_primary', 'full_name'],
                'unique_together': {('code_company', 'email')},
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('rating_5', 'Rating (1–5)'), ('rating_10', 'Rating (1–10)'), ('nps', 'NPS (0–10, would you recommend us)'), ('multiple_choice', 'Multiple choice'), ('yes_no', 'Yes / No'), ('open_text', 'Open text')], default='rating_5', max_length=20)),
                ('options', models.JSONField(blank=True, help_text='List of strings, only used when question_type=multiple_choice.', null=True)),
                ('scoring_dimension', models.CharField(choices=[('satisfaction', 'Satisfaction'), ('loyalty', 'Loyalty'), ('upsell_readiness', 'Upsell readiness'), ('none', 'Not scored (context only)')], default='none', max_length=20)),
                ('weight', models.FloatField(default=1.0, help_text='Relative weight within its scoring dimension.')),
                ('is_required', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.surveytemplate')),
            ],
            options={
                'ordering': ['template_id', 'order'],
            },
        ),
    ]
