# Generated by Django 6.0.7 on 2026-08-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontact',
            name='code_company',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
