# Generated by Django 6.0.7 on 2026-08-08 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_survey_surveyresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveytemplate',
            name='service_category',
            field=models.CharField(choices=[('web_dev', 'Web Development'), ('digital_marketing', 'Digital Marketing'), ('hosting_maintenance', 'Hosting & Maintenance'), ('consulting_service', 'Consulting'), ('other', 'Other / Generic')], default='other', max_length=30),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('survey_sent', 'Survey sent'), ('survey_completed', 'Survey completed')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(blank=True, default='', max_length=500)),
                ('code_company', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='surveys.survey')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
