# Generated by Django 6.0.7 on 2026-08-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_alter_surveytemplate_service_category_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='survey',
        ),
        migrations.AddField(
            model_name='notification',
            name='related_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('survey_sent', 'Survey sent'), ('survey_completed', 'Survey completed'), ('deal_created', 'Deal created'), ('deal_won', 'Deal won'), ('deal_lost', 'Deal lost'), ('project_created', 'Project created'), ('task_created', 'Task created')], max_length=30),
        ),
    ]
