# Generated by Django 6.0.7 on 2026-08-08 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_remove_notification_survey_notification_related_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Deactivated instead of deleted once the question has real answers (SurveyResponse.question is CASCADE — deleting it would silently wipe every past answer). Inactive questions are excluded from new sends and public fills but stay visible in the template editor.'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('survey_sent', 'Survey sent'), ('survey_completed', 'Survey completed'), ('verdict_ready', 'AI verdict ready'), ('deal_created', 'Deal created'), ('deal_won', 'Deal won'), ('deal_lost', 'Deal lost'), ('project_created', 'Project created'), ('task_created', 'Task created')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_type',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.CreateModel(
            name='SurveyVerdict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('satisfaction_score', models.FloatField(blank=True, null=True)),
                ('loyalty_score', models.FloatField(blank=True, null=True)),
                ('upsell_readiness_score', models.FloatField(blank=True, null=True)),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative'), ('mixed', 'Mixed')], default='', max_length=10)),
                ('summary', models.TextField(blank=True, default='')),
                ('risk_flags', models.JSONField(blank=True, default=list)),
                ('recommended_actions', models.JSONField(blank=True, default=list, help_text='List of {"label": str, "category": "retention|upsell|content|outreach|support"}.')),
                ('model_used', models.CharField(blank=True, default='', max_length=100)),
                ('error_message', models.TextField(blank=True, default='')),
                ('generation_count', models.PositiveIntegerField(default=0)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verdict', to='surveys.survey')),
            ],
        ),
    ]
