# Generated by Django 6.0.7 on 2026-08-10 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_surveyquestion_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='depends_on_question',
            field=models.ForeignKey(blank=True, help_text="If set, this question is only shown when depends_on_question's numeric answer is >= show_if_min_value.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependents', to='surveys.surveyquestion'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='excludes_selected_from',
            field=models.ForeignKey(blank=True, help_text="If set, whatever the client selected as the answer to this referenced question is removed from THIS question's option list at fill-time — e.g. 'services you use' feeding into 'services to explore next'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excluded_by', to='surveys.surveyquestion'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='origin',
            field=models.CharField(choices=[('manual', 'Manually authored'), ('default', 'Copied from default template'), ('industry', 'Copied from industry template'), ('ai_generated', 'AI-generated from subscription history')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='show_if_min_value',
            field=models.FloatField(blank=True, help_text="Threshold for depends_on_question's answer (e.g. 4 means 'only show if rated 4 or 5 stars'). Ignored if depends_on_question is not set.", null=True),
        ),
        migrations.AddField(
            model_name='surveytemplate',
            name='is_prepared_draft',
            field=models.BooleanField(default=False, help_text='True for the auto-assembled per-company draft created by prepare_survey_for_company() — hidden from the main template management list, shown only in the Prepare Survey review step.'),
        ),
        migrations.AddField(
            model_name='surveytemplate',
            name='prepared_for_code_company',
            field=models.CharField(blank=True, db_index=True, help_text='Set only on prepared-draft templates — one standing draft per company, reused until explicitly regenerated. NULL for every normal (manually managed) template.', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='question_type',
            field=models.CharField(choices=[('rating_5', 'Rating (1–5)'), ('rating_10', 'Rating (1–10)'), ('nps', 'NPS (0–10, would you recommend us)'), ('multiple_choice', 'Multiple choice (single-select)'), ('multi_select', 'Multiple choice (multi-select)'), ('yes_no', 'Yes / No'), ('open_text', 'Open text')], default='rating_5', max_length=20),
        ),
        migrations.AlterField(
            model_name='surveytemplate',
            name='industry',
            field=models.CharField(choices=[('manufacturing', 'Manufacturing'), ('services', 'Services'), ('tourism', 'Tourism'), ('food_beverage', 'Food & Beverage'), ('ngo_development', 'NGO & Development Organization'), ('banking', 'Banking'), ('education', 'Education'), ('advertising_marketing', 'Advertising & Marketing'), ('staffing_recruitment', 'Staffing & Recruitment'), ('telecom', 'Telecom'), ('postal_services', 'Postal Services'), ('other', 'Other / Generic')], default='other', max_length=30),
        ),
    ]
