# Generated by Django 6.0.7 on 2026-08-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_surveyquestion_depends_on_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='sent_by_email',
            field=models.EmailField(blank=True, default='', help_text='Email of whoever was logged in when this survey was sent — captured from the frontend since Django itself has no auth layer. Used as the default recipient for the AI next-steps report.', max_length=254),
        ),
        migrations.AddField(
            model_name='surveyverdict',
            name='next_steps_report',
            field=models.TextField(blank=True, default='', help_text='Longer, narrative next-steps report — a separate, more thorough LLM call than the short summary above. Emailed automatically to REPORT_RECIPIENT_EMAILS once generated.'),
        ),
    ]
