# Generated by Django 6.0.7 on 2026-08-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_survey_sent_by_email_surveyverdict_next_steps_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyverdict',
            name='report_send_error',
            field=models.TextField(blank=True, default='', help_text='Populated if the most recent report-email attempt failed (e.g. no recipient available). Cleared on a successful send.'),
        ),
        migrations.AddField(
            model_name='surveyverdict',
            name='report_sent_at',
            field=models.DateTimeField(blank=True, help_text='Set when the next-steps PDF report was successfully emailed. NULL if it was never sent, or the most recent attempt failed.', null=True),
        ),
    ]
