# Generated by Django 6.0.7 on 2026-08-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_surveyverdict_report_send_error_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyCleanupRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ran_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cutoff_days', models.PositiveIntegerField()),
                ('was_dry_run', models.BooleanField(default=False)),
                ('deleted_count', models.PositiveIntegerField(default=0)),
                ('details', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-ran_at'],
            },
        ),
    ]
