# Generated by Django 6.0.7 on 2026-08-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('revenue_deals', 'Revenue & Deals'), ('customer_churn_b2c', 'B2C Customers & Churn'), ('customer_churn_b2b', 'B2B Customers & Churn'), ('projects', 'Projects')], max_length=25, unique=True)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('failed', 'Failed')], default='ready', max_length=10)),
                ('items', models.JSONField(blank=True, default=list, help_text='List of {"tone": "primary|warning|destructive", "title": str, "body": str}, max 3 items.')),
                ('model_used', models.CharField(blank=True, default='', max_length=100)),
                ('error_message', models.TextField(blank=True, default='')),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
